[
  {
    "id": 1,
    "name": "مدير المستشفى",
    "name_en": "Hospital Manager",
    "ext": "9090",
    "more_ext": "9091 - 9007",
    "phone": "0144259090",
    "email": "",
    "location": "المبنى الرئيسي - الدور الأرضي",
    "location_en": "Main Building - Ground Floor",
    "img": "/",
    
  },
  {
    "id": 2,
    "name": "السنترال",
    "name_en": "Central",
    "ext": "8",
    "more_ext": "7070",
    "phone": "",
    "email": "",
    "location": "المبنى الرئيسي - القبو",
    "location_en": "Main Building - Basement",
    "img": "/Central.png",
    
  },
  {
    "id": 3,
    "name": "العيادات الخارجية - عيادة العيون",
    "name_en": "OPD - Clinics Eye Clinic",
    "ext": "3032",
    "more_ext": "3031",
    "phone": "",
    "email": "",
    "location": "",
    "location_en": "Main Building - Basement",
    "img": "/",
    
  },
  {
    "id": 4,
    "name": "الصيانة - اصلاح الأعطال",
    "name_en": "Maintenance - Repair Faults",
    "ext": "6000",
    "more_ext": "",
    "phone": "",
    "email": "",
    "location": "مبنى الخدمات - الدور الثاني",
    "location_en": "Services Building - Second Floor",
    "img": "/22.png",
    
},
  {
    "id": 5,
    "name": "صيانة الحاسب",
    "name_en": "Movement",
    "ext": "4000",
    "more_ext": "4001-4002-4003-4004",
    "phone": "",
    "email": "",
    "location": "العيادات الخارجية - الدور الثاني",
    "location_en": "Opposite the service building",
    "img": "/55.png",
    
},
  {
    "id": 6,
    "name": "النظافة",
    "name_en": "Cleanliness",
    "ext": "6000",
    "more_ext": "",
    "phone": "",
    "email": "",
    "location": "المبنى الرئيسي - البدروم",
    "location_en": "Main Building - Basement",
    "img": "/cleanness.png",
    
},
  {
    "id": 7,
    "name": "الصيدلية - الداخلية",
    "name_en": "Pharmacy - Internal",
    "ext": "6000",
    "more_ext": "",
    "phone": "",
    "email": "",
    "location": "المبنى الرئيسي - البدروم",
    "location_en": "Main Building - Basement",
    "img": "/66.png",
    
},
  {
    "id": 8,
    "name": "الولادة - التنويم",
    "name_en": "Birth - Hypnosis",
    "ext": "1500",
    "more_ext": "1501",
    "phone": "",
    "email": "",
    "location": "المبنى الرئيسي - البدروم",
    "location_en": "Main Building - Basement",
    "img": "/Birth.png",
    
},
  {
    "id": 9,
    "name": "العيادات - عيادة العظام",
    "name_en": "OPD - Bones",
    "ext": "1500",
    "more_ext": "1501",
    "phone": "",
    "email": "",
    "location": "المبنى الرئيسي - البدروم",
    "location_en": "Main Building - Basement",
    "img": "/Bones.png",
    
}
  
]
